slogan: "Yet another bootstrap theme."

theme: yeti
inverse: false

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: Freemind
    url: https://github.com/wzpan/freemind/
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/wzpan
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: http://www.linkedin.com/in/hahack
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
  - search
  - category
  - tagcloud
  - recent_posts  
  - links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: false
jiathis: false

embed:
  download:
    info: http://localhost:5000/dl/api/info/%s/
    go: http://localhost:5000/dl/go/%s/
    root: http://localhost/blog/uploads
  pageview:
    info: http://localhost:5000/pv/api/info/%s/

