slogan: "Yet another bootstrap theme."

theme: yeti
inverse: false

menu:
  - title: Archives
    url: date/
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: category/
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tag/
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: Home
    url: http://zengrong.net
    intro: "曾嵘的主页"
    icon: "fa fa-user"

links:
  - title: Home
    url: http://zengrong.net
    intro: "zrong's blog"
    icon: "fa fa-home"
  - title: "西部秋虫"
    url: http://www.fmser.cn
    intro: "专注于Flash+FMS技术研究与应用"
    icon: "fa fa-bug"

widgets:
  - search
  - category
  - tagcloud
  - recent_posts
  - links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# SOHU Changyan
changyan:
  appid: cyrpy0Ose
  appkey: prod_73c235677a4c8e62e31453be11834285

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: false
jiathis: false

embed:
  download:
    info: http://aid.zengrong.net/dl/api/info/%s/
    go: http://aid.zengrong.net/dl/go/%s/
    root: http://blog.zengrong.net/uploads

pageview:
  info: http://aid.zengrong.net/pv/api/js/%s/
