slogan: "Every man dies but not every man really lives."

theme: yeti
inverse: false

menu:
  - title: Search
    url: search/
    intro: "搜索"
    icon: "fa fa-search"
  - title: Archives
    url: archive/
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: category/
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tag/
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: Links
    url: link/
    intro: "友情链接"
    icon: "fa fa-link"
  - title: Home
    url: https://zengrong.net
    intro: "曾嵘的主页"
    icon: "fa fa-user"

# 启用单独的 link 页面，不再需要这个 widget 了
# links:
#   - title: Home
#     url: http://zengrong.net
#     intro: "zrong's blog"
#     icon: "fa fa-home"

widgets:
  - search
  - category
  - tagcloud
  - recent_posts
#  - links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# SOHU Changyan
changyan:
  appid: cyrpy0Ose
  appkey: prod_73c235677a4c8e62e31453be11834285

# Analytics
google_analytics:
  enable: true
  siteid: UA-178999-6
baidu_tongji:
  enable: true
  siteid: 1d762cb3a96c330d5f860573627e073b

# search
search:
  # local: true
  # swiftype: ZP2ZSuHgipSZfRyU8uTR
  bing: true
  # baidu: true
  # qihoo: true
  # google: 010248203365983979668:happqssy-hw

# share widgets
bdshare: false
jiathis: false

embed:
  download:
    info: https://aid.zengrong.net/dl/api/info/%s/
    go: https://aid.zengrong.net/dl/go/%s/
    root: https://blog.zengrong.net/uploads

pageview:
  info: https://aid.zengrong.net/pv/api/js/%s/
